<!DOCTYPE html>
<html lang="en">
<head>
<style>
.table{
padding: 10px;
font-size:13px;
font-family: sans-serif;
}
table {
    border-collapse: collapse;
}
td {
    padding-top: 10px;
    padding-bottom: 10px;
}
</style>
</head>
<body>

    <?php //print_out($action); ?>

    <table class="table">
        <tr>
            <td colspan="2"><h3>Hi,</h3></td>
        </tr>
        <tr>
            <td colspan="2">You received this message because you registered an account in our website.
                            You need to activate your account first, in order to log in to our website.
            </td>
        </tr>
        <tr>
            <td colspan="2">Your username is <font style="color:blue;font-weight:700;"><?=$email?></td>
        </tr>
        <tr>
            <td colspan="2">To activate your account, please click on the following link:</td>
        </tr>
        <tr>
            <td colspan="2"><a href="<?= base_url() . $en_url?>" target="_blank"><?=  base_url() . $en_url?></a></td>
        </tr>
        <tr>
            <td colspan="2">Regards,<br/><br/> Administrator</td>
        </tr>
        <tr>
            <td colspan="2" style="height:50px;">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">==============This message generated by system, please do not reply.==============</td>
        </tr>  
    </table>

</body>

</html>
